version: '2'
services:
    mini_market-app:
        image: mini_market
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mini_market-mysql:3306/mini_market?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    mini_market-mysql:
        extends:
            file: mysql.yml
            service: mini_market-mysql
